-- JobFit Checker schema.
--
-- All three services share this schema (a documented simplification -- see
-- the README's "Known limitations" section for the database-per-service
-- alternative). Applied once at container startup by the Postgres image's
-- /docker-entrypoint-initdb.d mechanism; Spring's ddl-auto is set to
-- "validate" everywhere, not "update" -- the schema is owned here, not
-- generated by Hibernate.

CREATE TABLE jobs (
    id              BIGSERIAL PRIMARY KEY,
    title           VARCHAR(200)  NOT NULL,
    description     TEXT          NOT NULL,
    required_skills JSONB         NOT NULL DEFAULT '[]',
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE resumes (
    id                BIGSERIAL PRIMARY KEY,
    job_id            BIGINT       NOT NULL REFERENCES jobs(id),
    candidate_name    VARCHAR(200) NOT NULL,
    original_filename VARCHAR(500) NOT NULL,
    content_type      VARCHAR(100) NOT NULL,
    storage_key       VARCHAR(500) NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'UPLOADED',
    failure_reason    TEXT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_resumes_job_id ON resumes(job_id);
CREATE INDEX idx_resumes_status ON resumes(status);

-- One row per resume, written once by parsing-service's second parsing stage.
CREATE TABLE parsed_resumes (
    resume_id         BIGINT PRIMARY KEY REFERENCES resumes(id),
    extracted_text    TEXT         NOT NULL,
    skills            JSONB        NOT NULL DEFAULT '[]',
    years_experience  INTEGER,
    education         VARCHAR(500),
    parsed_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- One row per resume, written once by analysis-service.
CREATE TABLE analysis_results (
    id                  BIGSERIAL PRIMARY KEY,
    job_id              BIGINT       NOT NULL REFERENCES jobs(id),
    resume_id           BIGINT       NOT NULL UNIQUE REFERENCES resumes(id),
    qualification_score NUMERIC(5,2) NOT NULL,
    matched_skills      JSONB        NOT NULL DEFAULT '[]',
    missing_skills      JSONB        NOT NULL DEFAULT '[]',
    suggestions         TEXT         NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Transactional outbox: the event-driven backbone that decouples
-- api-service (producer of resume.uploaded) from parsing-service (producer
-- of resume.parsed / consumer of resume.uploaded) from analysis-service
-- (consumer of resume.parsed), without a message broker or cloud queue.
-- Multiple instances of the same service compete safely for rows via
-- `SELECT ... FOR UPDATE SKIP LOCKED`, which is what makes each service
-- horizontally scalable: adding a second parsing-service instance just
-- means two workers racing for the same PENDING rows, each guaranteed to
-- claim a disjoint set.
CREATE TABLE event_outbox (
    id            BIGSERIAL PRIMARY KEY,
    topic         VARCHAR(100) NOT NULL,
    payload       JSONB        NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING', -- PENDING | PROCESSING | PROCESSED | FAILED
    attempts      INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed_at  TIMESTAMPTZ,
    processed_by  VARCHAR(100)
);

CREATE INDEX idx_event_outbox_topic_status ON event_outbox(topic, status);
